In [2]:
import numpy as np
import pandas as pd

In [3]:
# 1. Привести различные способы создания объектов типа Series
# Для создания Series можно использовать
# - списки Python или массивы NumPy
my_list = ['a', 2, 3, 'd', 5]
my_array = np.array([1, 2, 3, 4, 5])
data_1 = pd.Series(my_list)
data_2 = pd.Series(my_array)
print(data_1)
print(data_2)

0    a
1    2
2    3
3    d
4    5
dtype: object
0    1
1    2
2    3
3    4
4    5
dtype: int32

In [4]:
# - скалярные значение
data_3 = pd.Series('d', index=[1, 2, 3])
data_4 = pd.Series(6, index=[10, 20, 30])
print(data_3)
print(data_4)

1    d
2    d
3    d
dtype: object
10    6
20    6
30    6
dtype: int64

In [5]:
# - словари
my_dict = {1: 'a', 2: 'b', 3: 'c'}
data_5 = pd.Series(my_dict)
print(data_5)

1    a
2    b
3    c
dtype: object

In [6]:
# 2. Привести различные способы создания объектов типа DataFrame
# DataFrame. Способы создания
# - через объекты Series
data_series = pd.Series([1, 2, 's', 4])
data_6 = pd.DataFrame(data_series)
print(data_6)

   0
0  1
1  2
2  s
3  4

In [7]:
# - списки словарей
dict_1 = [{1: 'a', 2: 'b', 3: 'c'}, {1: 'd', 2: 'e', 3: 'g'}]
data_7 = pd.DataFrame(dict_1, index=['first dict', 'second dict'])
print(data_7)

             1  2  3
first dict   a  b  c
second dict  d  e  g

In [8]:
# - словари объектов Series
dict_series = {1: pd.Series(['a', 'b', 'c'], index=['one', 'two', 'three']), 2: pd.Series(['d', 'e', 'f'], index=['one', 'two', 'three'])}
data_8 = pd.DataFrame(dict_series)
print(data_8)

       1  2
one    a  d
two    b  e
three  c  f

In [9]:
# - двумерный массив NumPy
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
data_9 = pd.DataFrame(array_1)
print(data_9)

   0  1  2
0  1  2  3
1  4  5  6

In [10]:
# - структурированный массив Numpy
data = np.zeros(2, dtype = {'names': ('name', 'age'), 'formats': ('U10', 'i4')})
name = ['name1', 'name2']
age = [30, 40]

data['name'] = name
data['age'] = age

data_10 = pd.DataFrame(data, index=['first person', 'second person'])

print(data_10)

                name  age
first person   name1   30
second person  name2   40

In [13]:
# 3. Объедините два объекта Series с неодинаковыми множествами ключей (индексов) так, чтобы вместо NaN было установлено значение 1
pop = pd.Series(
    {
        'city_1': 1001,
        'city_2': 1002,
        'city_3': 1003,
        'city_41': 1004,
        'city_51': 1005,
    })

area = pd.Series(
    {   'city_1': 9991,
        'city_2': 9992,
        'city_3': 9993,
        'city_42': 9994,
        'city_52': 9995,
    })

data = pd.DataFrame({'area1': area, 'pop1': pop})
data = data.fillna(1)
print(data)

          area1    pop1
city_1   9991.0  1001.0
city_2   9992.0  1002.0
city_3   9993.0  1003.0
city_41     1.0  1004.0
city_42  9994.0     1.0
city_51     1.0  1005.0
city_52  9995.0     1.0

In [24]:
# 4. Переписать пример с транслирование для DataFrame так, чтобы вычитание происходило по СТОЛБЦАМ
rng = np.random.default_rng(1)
A = rng.integers(0, 10, (3, 4))
df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
print(df)
print(df.iloc[::, 0])
print((df.T - df.iloc[::, 0]).T)

   a  b  c  d
0  4  5  7  9
1  0  1  8  9
2  2  3  8  4
0    4
1    0
2    2
Name: a, dtype: int64
   a  b  c  d
0  0  1  3  5
1  0  1  8  9
2  0  1  6  2

In [43]:
# 5. На примере объектов DataFrame и Series продемонстрируйте использование методов ffill() и bfill()
df = pd.DataFrame([[np.nan, 1, 2], [np.nan, np.nan, np.nan], [3, 4, np.nan]], columns=['a', 'b', 'c'])
s = pd.Series([1, 2, 3, np.nan, 4, np.nan])
print(df)
print(s)

     a    b    c
0  NaN  1.0  2.0
1  NaN  NaN  NaN
2  3.0  4.0  NaN
0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [44]:
df.ffill() # заменяет пропущенные значения предыдущим допустимым значением в столбце

     a    b    c
0  NaN  1.0  2.0
1  NaN  1.0  2.0
2  3.0  4.0  2.0

In [45]:
s.ffill()

0    1.0
1    2.0
2    3.0
3    3.0
4    4.0
5    4.0
dtype: float64

In [47]:
df.bfill() # заменяет пропущенные значения следующим допустимым значением в столбце

     a    b    c
0  3.0  1.0  2.0
1  3.0  4.0  NaN
2  3.0  4.0  NaN

In [48]:
s.bfill()

0    1.0
1    2.0
2    3.0
3    4.0
4    4.0
5    NaN
dtype: float64